// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstzfTEbMOBzPwNuIIZFW4N1rzKOP8f_U',
    appId: '1:4097325442:web:e78db459e122469ccd379b',
    messagingSenderId: '4097325442',
    projectId: 'cleango-865d6',
    authDomain: 'cleango-865d6.firebaseapp.com',
    storageBucket: 'cleango-865d6.firebasestorage.app',
    measurementId: 'G-41549DD5QY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjSflM-bmPIsZdxNWWOvgH_xygDC27j7g',
    appId: '1:4097325442:ios:71bfe90efa957c1ecd379b',
    messagingSenderId: '4097325442',
    projectId: 'cleango-865d6',
    storageBucket: 'cleango-865d6.firebasestorage.app',
    iosBundleId: 'com.example.carWashManagmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjSflM-bmPIsZdxNWWOvgH_xygDC27j7g',
    appId: '1:4097325442:ios:71bfe90efa957c1ecd379b',
    messagingSenderId: '4097325442',
    projectId: 'cleango-865d6',
    storageBucket: 'cleango-865d6.firebasestorage.app',
    iosBundleId: 'com.example.carWashManagmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCstzfTEbMOBzPwNuIIZFW4N1rzKOP8f_U',
    appId: '1:4097325442:web:d16d565c68b3db3fcd379b',
    messagingSenderId: '4097325442',
    projectId: 'cleango-865d6',
    authDomain: 'cleango-865d6.firebaseapp.com',
    storageBucket: 'cleango-865d6.firebasestorage.app',
    measurementId: 'G-E9N3EGMDJN',
  );
}
